### ISSUE TITLE
Plugin breaks builds in 2020.3

### ISSUE THREAD

**Issue by heldev** [fkorotkov/intellij-thrift#95]
If the plugin is enabled builds (at least Build -> Rebuild Project) fail with the following message
`Module '<my-module-name>' tests: java.lang.NoClassDefFoundError: com/intellij/util/messages/Topic`
